services:
  backend:
    build: ./backend
    # tty: true
    # command: /bin/bash
    command: mix phx.server
    env_file: .env
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/contributio_dev
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - postgres

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contributio_dev
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

  frontend:
    # tty: true
    # command: /bin/bash
    command: yarn dev
    build: ./frontend
    volumes:
      - ./frontend:/app
    env_file: .env
    environment:
      - NODE_ENV=development
      - ALLOW_ENDPOINT=$FRONTEND_URI/allow
      - GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
    ports:
      - "1234:1234" # dev server port
      - "1235:1235" # HMR server port
    depends_on: 
      - backend

volumes:
  db-data:
  pgadmin:

networks:
  postgres:
    driver: bridge