version: '3'

services:
  web:
    image: docker-phoenix
    command: mix phx.server
    env_file: .env
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DATABASE_URL=ecto://postgres:postgres@postgres/contributio_dev
      - NODE_ENV=development
      - ROOT_URI=$ROOT_URI
      - ALLOW_ENDPOINT=$ROOT_URI/allow
      - GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
    volumes:
      - .:/app
      - ./front:/app/priv/static/js
      - ./front/node_modules:/app/front/node_modules
    ports:
      - "4000:4000"
    links:
      - postgres

  postgres:
    image: postgres:9.6.5
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"