version: '3'

services:
  web:
    image: docker-phoenix
    command: mix phx.server
    env_file: .env
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DATABASE_URL=ecto://postgres:postgres@postgres/contributio_dev
      - NODE_ENV=development
      - ALLOW_ENDPOINT=http://localhost:4000/allow
      - GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
    volumes:
      - .:/app
      - ./front:/app/priv/static/js
      - ./front/node_modules:/app/front/node_modules
    ports:
      - "4000:4000"
    links:
      - postgres

  postgres:
    image: postgres:9.6.5
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
      - "1234:1234" # dev server port
      - "1235:1235" # HMR server port

  # front:
  #   depends_on: 
  #     - web
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend:/app
  #     - ./frontend/node_modules:/app/node_modules
  #   env_file: .env
  #   environment:
  #     - NODE_ENV=development
  #     - ALLOW_ENDPOINT=$FRONTEND_URI/allow
  #     - GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
  #   command: yarn dev --hmr-port 1235
  #   ports:
  #     - "1234:1234" # dev server port
  #     - "1235:1235" # HMR server port